const catalogProduct = [
   
    {
        id: 'item1',
        name: 'Пальто',
        description: 'Пальто женское',
        sex: 'WM',
        color: '#fff',
        img: './img/palto1.jpeg',
        price: 150.00,
    },
    {
        id: 'item2',
        name: 'Джинсы',
        description: 'Джинсы мужские',
        sex: 'M',
        color: 'black',
        img: './img/dzins.jpeg',
        price: 29.00,
    },
    {
        id: 'item3',
        name: 'Рубашки',
        description: 'Рубашка мужская',
        sex: 'M',
        color: 'black',
        img: './img/rubashka.jpeg',
        price: 50.00,
    },
    {
        id: 'item4',
        name: 'Пальто',
        description: 'Пальто женское',
        sex: 'WM',
        color: '#fff',
        img: './img/palto1.jpeg',
        price: 150.00,
    },
    {
        id: 'item5',
        name: 'Джинсы',
        description: 'Джинсы мужские',
        sex: 'M',
        color: 'black',
        img: './img/dzins.jpeg',
        price: 29.00,
    },
    {
        id: 'item6',
        name: 'Рубашки',
        description: 'Рубашка мужская',
        sex: 'M',
        color: 'black',
        img: './img/rubashka.jpeg',
        price: 50.00,
    }, 
    {
        id: 'item7',
        name: 'Пальто',
        description: 'Пальто женское',
        sex: 'WM',
        color: '#fff',
        img: './img/palto1.jpeg',
        price: 150.00,
    },
    {
        id: 'item8',
        name: 'Джинсы',
        description: 'Джинсы мужские',
        sex: 'M',
        color: 'black',
        img: './img/dzins.jpeg',
        price: 29.00,
    },
    {
        id: 'item9',
        name: 'Рубашки',
        description: 'Рубашка мужская',
        sex: 'M',
        color: 'black',
        img: './img/rubashka.jpeg',
        price: 50.00,
    }
];
    